#!/bin/bash
docker run --name Abathur -v $HOME:/root -p 3000:3000 -dit python:2-slim
docker exec Abathur pip install flask
docker exec Abathur bash -c "echo -e 'from flask import Flask\napp = Flask(__name__)\n\n@app.route(\"/\")\ndef hello_world():\n\treturn \"<h1>Hello World</h1>\"\n\nif __name__ == \"__main__\":\n\tapp.run()' > /root/hw.py"
docker exec --env FLASK_APP=/root/hw.py Abathur flask run --host=0.0.0.0 --port=3000
# open http://192.168.99.100:3000
